POST /api/2.4/inspections HTTP/1.0
Authorization: Basic dGVzdF9zYXNfdG9rZW46
Content-Length: 291
Content-Type: application/json
Host: audit-api-dev.prozorro.gov.ua

{
  "data": {
    "description": "Inspection is an official visit to a building or organization to check that everything is satisfactory and that rules are being obeyed", 
    "monitoring_ids": [
      "a6b2b18977f24277b238c7b7a5342b1d", 
      "580997bb06674235801d75f2f6e6c6c6", 
      "2c5cc4a289d747a5b8dacd72adaea4d9"
    ]
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://audit-api-dev.prozorro.gov.ua/api/2.4/inspections/1e3a0b5187993d98829b70c32c006d62

{
  "data": {
    "description": "Inspection is an official visit to a building or organization to check that everything is satisfactory and that rules are being obeyed", 
    "monitoring_ids": [
      "a6b2b18977f24277b238c7b7a5342b1d", 
      "580997bb06674235801d75f2f6e6c6c6", 
      "2c5cc4a289d747a5b8dacd72adaea4d9"
    ], 
    "dateModified": "2018-01-01T02:00:00+02:00", 
    "inspection_id": "UA-I-2018-01-01-000001", 
    "dateCreated": "2018-01-01T02:00:00+02:00", 
    "id": "1e3a0b5187993d98829b70c32c006d62"
  }
}

